import SwiftUI

// MARK: - Dua Category
struct DuaCategory: Identifiable {
    let id = UUID()
    let title: String
    let icon: String
    let color: Color
    let duas: [DuaEntry]
}

struct DuaEntry: Identifiable {
    let id = UUID()
    let number: Int
    let title: String
    let arabic: String
    let transliteration: String
    let translation: String
    let reference: String
    var isFavorite: Bool = false
}

// MARK: - Dua Database
struct DuaDatabase {

    static let morning = DuaCategory(
        title: "Morning",
        icon: "sunrise.fill",
        color: Color.alehaAmber,
        duas: [
            DuaEntry(number: 1, title: "Morning Remembrance",
                     arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ",
                     transliteration: "Asbahna wa asbahal mulku lillahi walhamdu lillah",
                     translation: "We have entered the morning and at this very time the dominion belongs to Allah, and all praise is for Allah.",
                     reference: "Abu Dawud 5076"),
            DuaEntry(number: 2, title: "Gratitude at Dawn",
                     arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ",
                     transliteration: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu",
                     translation: "O Allah, by Your leave we have reached the morning and by Your leave we have reached the evening, by Your leave we live and die.",
                     reference: "Tirmidhi 3391"),
            DuaEntry(number: 3, title: "Seeking Allah's Blessing",
                     arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ",
                     transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduk",
                     translation: "O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am Your servant.",
                     reference: "Bukhari 6306"),
            DuaEntry(number: 4, title: "Protection from Evil",
                     arabic: "أَعُوذُ بِاللَّهِ السَّمِيعِ الْعَلِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
                     transliteration: "A'udhu billahis-sami'il 'alimi minash-shaytanir-rajim",
                     translation: "I seek refuge in Allah, the All-Hearing, All-Knowing, from the accursed devil.",
                     reference: "Abu Dawud 775"),
            DuaEntry(number: 5, title: "Morning Tasbih",
                     arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
                     transliteration: "Subhanallahi wa bihamdih",
                     translation: "Glory be to Allah and praise be to Him.",
                     reference: "Bukhari 6405"),
            DuaEntry(number: 6, title: "Complete Trust",
                     arabic: "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
                     transliteration: "Hasbiyallahu la ilaha illa huwa, 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim",
                     translation: "Allah is sufficient for me. There is no god but Him. I have placed my trust in Him, He is Lord of the Majestic Throne.",
                     reference: "Abu Dawud 5081"),
            DuaEntry(number: 7, title: "Seeking Good Day",
                     arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ فَتْحَهُ وَنَصْرَهُ وَنُورَهُ وَبَرَكَتَهُ وَهُدَاهُ",
                     transliteration: "Allahumma inni as'aluka khayra hadhal-yawm, fathahu wa nasrahu wa nurahu wa barakatahu wa hudahu",
                     translation: "O Allah, I ask You for the good of this day, its victory, its light, its blessings and its guidance.",
                     reference: "Abu Dawud 5084"),
            DuaEntry(number: 8, title: "Ayat al-Kursi",
                     arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
                     transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum",
                     translation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence.",
                     reference: "Quran 2:255"),
            DuaEntry(number: 9, title: "Gratitude for Life",
                     arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
                     transliteration: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
                     translation: "All praise is for Allah who gave us life after causing us to die, and unto Him is the resurrection.",
                     reference: "Bukhari 6312"),
            DuaEntry(number: 10, title: "Seeking Forgiveness",
                     arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ",
                     transliteration: "Astaghfirullaha al-'azim alladhi la ilaha illa huwal-hayyul-qayyumu wa atubu ilaih",
                     translation: "I seek forgiveness from Allah, the Mighty, whom there is none worthy of worship except Him, the Living, the Eternal, and I repent to Him.",
                     reference: "Tirmidhi 3577"),
            DuaEntry(number: 11, title: "Surah Al-Ikhlas",
                     arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ",
                     transliteration: "Qul huwallahu ahad",
                     translation: "Say: He is Allah, the One.",
                     reference: "Quran 112:1"),
            DuaEntry(number: 12, title: "Morning Salawat",
                     arabic: "اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ",
                     transliteration: "Allahumma salli wa sallim 'ala nabiyyina Muhammad",
                     translation: "O Allah, bestow peace and blessings upon our Prophet Muhammad.",
                     reference: "Hadith")
        ]
    )

    static let evening = DuaCategory(
        title: "Evening",
        icon: "sunset.fill",
        color: Color.alehaDarkGreen,
        duas: [
            DuaEntry(number: 1, title: "Evening Remembrance",
                     arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ",
                     transliteration: "Amsayna wa amsal-mulku lillahi walhamdu lillah",
                     translation: "We have entered the evening and at this very time the dominion belongs to Allah, and all praise is for Allah.",
                     reference: "Abu Dawud 5076"),
            DuaEntry(number: 2, title: "Before Sleep",
                     arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
                     transliteration: "Bismika Allahumma amutu wa ahya",
                     translation: "In Your name, O Allah, I die and I live.",
                     reference: "Bukhari 6312"),
            DuaEntry(number: 3, title: "Sleep Protection",
                     arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
                     transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak",
                     translation: "O Allah, protect me from Your punishment on the Day You resurrect Your servants.",
                     reference: "Abu Dawud 5045"),
            DuaEntry(number: 4, title: "Seeking Forgiveness",
                     arabic: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
                     transliteration: "Astaghfirullaha wa atubu ilayh",
                     translation: "I seek forgiveness from Allah and repent to Him.",
                     reference: "Bukhari 6307"),
            DuaEntry(number: 5, title: "Evening Tasbih",
                     arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
                     transliteration: "Subhanallahi wa bihamdih",
                     translation: "Glory be to Allah and all praise is for Him.",
                     reference: "Bukhari 6405"),
            DuaEntry(number: 6, title: "Gratitude for Evening",
                     arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ",
                     transliteration: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu",
                     translation: "O Allah, by Your leave we have reached the evening and by Your leave we have reached the morning, by Your leave we live and die.",
                     reference: "Tirmidhi 3391"),
            DuaEntry(number: 7, title: "Evening Protection",
                     arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
                     transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
                     translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
                     reference: "Muslim 2708"),
            DuaEntry(number: 8, title: "Heart at Peace",
                     arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
                     transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan",
                     translation: "O Allah, I seek Your protection from anxiety and grief.",
                     reference: "Bukhari 2893"),
            DuaEntry(number: 9, title: "Seeking Good Night",
                     arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا فِيهَا",
                     transliteration: "Allahumma inni as'aluka khayra hadhihil-laylati wa khayra ma fiha",
                     translation: "O Allah, I ask You for the goodness of this night and the goodness of what is in it.",
                     reference: "Muslim 2723"),
            DuaEntry(number: 10, title: "Dua Before Sleep",
                     arabic: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ وَفَوَّضْتُ أَمْرِي إِلَيْكَ",
                     transliteration: "Allahumma aslamtu nafsi ilayk wa fawwadtu amri ilayk",
                     translation: "O Allah, I have submitted myself to You and entrusted my affairs to You.",
                     reference: "Bukhari 247"),
            DuaEntry(number: 11, title: "Ayat al-Kursi",
                     arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
                     transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum",
                     translation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence.",
                     reference: "Quran 2:255"),
            DuaEntry(number: 12, title: "Evening Salawat",
                     arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
                     transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
                     translation: "O Allah, send blessings upon Muhammad and the family of Muhammad.",
                     reference: "Bukhari 3370")
        ]
    )

    static let travel = DuaCategory(
        title: "Travel",
        icon: "airplane",
        color: Color.alehaGreen,
        duas: [
            DuaEntry(number: 1, title: "Starting a Journey",
                     arabic: "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ",
                     transliteration: "Allahu Akbar, Allahu Akbar, Allahu Akbar",
                     translation: "Allah is the Greatest, Allah is the Greatest, Allah is the Greatest.",
                     reference: "Muslim 1342"),
            DuaEntry(number: 2, title: "Boarding a Vehicle",
                     arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ",
                     transliteration: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin",
                     translation: "Glory be to Him Who has subjected this to us, and we were not capable of that.",
                     reference: "Quran 43:13"),
            DuaEntry(number: 3, title: "Returning Home",
                     arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
                     transliteration: "Ayibuna, ta'ibuna, 'abiduna, lirabbina hamidun",
                     translation: "We are returning, repenting, worshipping, and praising our Lord.",
                     reference: "Bukhari 1797"),
            DuaEntry(number: 4, title: "Entering a Town",
                     arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهَا",
                     transliteration: "Allahumma barik lana fiha",
                     translation: "O Allah, bless us in it.",
                     reference: "Muslim 1343"),
            DuaEntry(number: 5, title: "Rest During Travel",
                     arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
                     transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
                     translation: "I seek refuge in the perfect words of Allah from the evil of that which He created.",
                     reference: "Muslim 2708"),
            DuaEntry(number: 6, title: "Safety in Travel",
                     arabic: "اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الأَهْلِ",
                     transliteration: "Allahumma antas-sahibu fis-safari wal-khalifatu fil-ahl",
                     translation: "O Allah, You are the Companion in travel and the Guardian of the family.",
                     reference: "Muslim 1342"),
            DuaEntry(number: 7, title: "Climbing High Ground",
                     arabic: "اللَّهُ أَكْبَرُ",
                     transliteration: "Allahu Akbar",
                     translation: "Allah is the Greatest.",
                     reference: "Bukhari 2993"),
            DuaEntry(number: 8, title: "Descending",
                     arabic: "سُبْحَانَ اللَّهِ",
                     transliteration: "Subhanallah",
                     translation: "Glory be to Allah.",
                     reference: "Bukhari 2993")
        ]
    )

    static let protection = DuaCategory(
        title: "Protection",
        icon: "shield.fill",
        color: Color(red: 0.55, green: 0.30, blue: 0.85),
        duas: [
            DuaEntry(number: 1, title: "Complete Protection",
                     arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
                     transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
                     translation: "I seek refuge in the perfect words of Allah from the evil of that which He has created.",
                     reference: "Muslim 2708"),
            DuaEntry(number: 2, title: "From Envy and Evil Eye",
                     arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
                     transliteration: "A'udhu billahi minash-shaytanir-rajim",
                     translation: "I seek refuge in Allah from the accursed devil.",
                     reference: "Quran 16:98"),
            DuaEntry(number: 3, title: "Surah Al-Falaq",
                     arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ مِنْ شَرِّ مَا خَلَقَ",
                     transliteration: "Qul a'udhu biraббil-falaq, min sharri ma khalaq",
                     translation: "Say: I seek refuge in the Lord of the daybreak, from the evil of what He has created.",
                     reference: "Quran 113:1-2"),
            DuaEntry(number: 4, title: "Surah An-Nas",
                     arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ مَلِكِ النَّاسِ إِلَهِ النَّاسِ",
                     transliteration: "Qul a'udhu birabbin-nas, malikin-nas, ilahin-nas",
                     translation: "Say: I seek refuge in the Lord of mankind, the King of mankind, the God of mankind.",
                     reference: "Quran 114:1-3"),
            DuaEntry(number: 5, title: "Ayat al-Kursi",
                     arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
                     transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum",
                     translation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence.",
                     reference: "Quran 2:255"),
            DuaEntry(number: 6, title: "Leaving Home",
                     arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
                     transliteration: "Bismillahi tawakkaltu 'alallahi wa la hawla wa la quwwata illa billah",
                     translation: "In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.",
                     reference: "Abu Dawud 5095"),
            DuaEntry(number: 7, title: "Entering Home",
                     arabic: "بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا",
                     transliteration: "Bismillahi walajna wa bismillahi kharajna",
                     translation: "In the name of Allah we enter and in the name of Allah we leave.",
                     reference: "Abu Dawud 5096"),
            DuaEntry(number: 8, title: "Against Anxiety",
                     arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ",
                     transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani wal-'ajz",
                     translation: "O Allah, I seek Your refuge from anxiety, grief and incapacity.",
                     reference: "Bukhari 6369"),
            DuaEntry(number: 9, title: "Before Eating",
                     arabic: "بِسْمِ اللَّهِ",
                     transliteration: "Bismillah",
                     translation: "In the name of Allah.",
                     reference: "Bukhari 5376"),
            DuaEntry(number: 10, title: "Seeking Strength",
                     arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
                     transliteration: "La hawla wa la quwwata illa billah",
                     translation: "There is no might or power except with Allah.",
                     reference: "Bukhari 7386")
        ]
    )

    static let all: [DuaCategory] = [morning, evening, travel, protection]
}
