import Foundation

// MARK: - All 114 Surahs
struct QuranData {
    static let allSurahs: [SurahInfo] = [
        SurahInfo(id:1,nameArabic:"الفاتحة",nameEnglish:"Al-Fatihah",nameTransliteration:"Al-Faatiha",meaning:"The Opening",verses:7,type:"Meccan",juz:1,nameMalayalam:"അൽ-ഫാതിഹ"),
        SurahInfo(id:2,nameArabic:"البقرة",nameEnglish:"Al-Baqarah",nameTransliteration:"Al-Baqara",meaning:"The Cow",verses:286,type:"Medinan",juz:1,nameMalayalam:"അൽ-ബഖറ"),
        SurahInfo(id:3,nameArabic:"آل عمران",nameEnglish:"Aal-E-Imran",nameTransliteration:"Aal-i-Imraan",meaning:"The Family of Imran",verses:200,type:"Medinan",juz:3,nameMalayalam:"ആൽ-ഇംറാൻ"),
        SurahInfo(id:4,nameArabic:"النساء",nameEnglish:"An-Nisa",nameTransliteration:"An-Nisaa",meaning:"The Women",verses:176,type:"Medinan",juz:4,nameMalayalam:"അൻ-നിസാ"),
        SurahInfo(id:5,nameArabic:"المائدة",nameEnglish:"Al-Maidah",nameTransliteration:"Al-Maaida",meaning:"The Table Spread",verses:120,type:"Medinan",juz:6,nameMalayalam:"അൽ-മാഇദ"),
        SurahInfo(id:6,nameArabic:"الأنعام",nameEnglish:"Al-Anam",nameTransliteration:"Al-An'aam",meaning:"The Cattle",verses:165,type:"Meccan",juz:7,nameMalayalam:"അൽ-അൻആം"),
        SurahInfo(id:7,nameArabic:"الأعراف",nameEnglish:"Al-Araf",nameTransliteration:"Al-A'raaf",meaning:"The Heights",verses:206,type:"Meccan",juz:8,nameMalayalam:"അൽ-അഅ്‌റാഫ്"),
        SurahInfo(id:8,nameArabic:"الأنفال",nameEnglish:"Al-Anfal",nameTransliteration:"Al-Anfaal",meaning:"The Spoils of War",verses:75,type:"Medinan",juz:9,nameMalayalam:"അൽ-അൻഫാൽ"),
        SurahInfo(id:9,nameArabic:"التوبة",nameEnglish:"At-Tawbah",nameTransliteration:"At-Tawba",meaning:"The Repentance",verses:129,type:"Medinan",juz:10,nameMalayalam:"അത്തവ്ബ"),
        SurahInfo(id:10,nameArabic:"يونس",nameEnglish:"Yunus",nameTransliteration:"Yunus",meaning:"Jonah",verses:109,type:"Meccan",juz:11,nameMalayalam:"യൂനസ്"),
        SurahInfo(id:11,nameArabic:"هود",nameEnglish:"Hud",nameTransliteration:"Hud",meaning:"Hud",verses:123,type:"Meccan",juz:11,nameMalayalam:"ഹൂദ്"),
        SurahInfo(id:12,nameArabic:"يوسف",nameEnglish:"Yusuf",nameTransliteration:"Yusuf",meaning:"Joseph",verses:111,type:"Meccan",juz:12,nameMalayalam:"യൂസഫ്"),
        SurahInfo(id:13,nameArabic:"الرعد",nameEnglish:"Ar-Rad",nameTransliteration:"Ar-Ra'd",meaning:"The Thunder",verses:43,type:"Medinan",juz:13,nameMalayalam:"അർ-റഅദ്"),
        SurahInfo(id:14,nameArabic:"إبراهيم",nameEnglish:"Ibrahim",nameTransliteration:"Ibrahim",meaning:"Abraham",verses:52,type:"Meccan",juz:13,nameMalayalam:"ഇബ്‌റാഹിം"),
        SurahInfo(id:15,nameArabic:"الحجر",nameEnglish:"Al-Hijr",nameTransliteration:"Al-Hijr",meaning:"The Rocky Tract",verses:99,type:"Meccan",juz:14,nameMalayalam:"അൽ-ഹിജ്‌ർ"),
        SurahInfo(id:16,nameArabic:"النحل",nameEnglish:"An-Nahl",nameTransliteration:"An-Nahl",meaning:"The Bee",verses:128,type:"Meccan",juz:14,nameMalayalam:"അൻ-നഹ്‌ൽ"),
        SurahInfo(id:17,nameArabic:"الإسراء",nameEnglish:"Al-Isra",nameTransliteration:"Al-Israa",meaning:"The Night Journey",verses:111,type:"Meccan",juz:15,nameMalayalam:"അൽ-ഇസ്രാ"),
        SurahInfo(id:18,nameArabic:"الكهف",nameEnglish:"Al-Kahf",nameTransliteration:"Al-Kahf",meaning:"The Cave",verses:110,type:"Meccan",juz:15,nameMalayalam:"അൽ-കഹ്‌ഫ്"),
        SurahInfo(id:19,nameArabic:"مريم",nameEnglish:"Maryam",nameTransliteration:"Maryam",meaning:"Mary",verses:98,type:"Meccan",juz:16,nameMalayalam:"മറിയം"),
        SurahInfo(id:20,nameArabic:"طه",nameEnglish:"Taha",nameTransliteration:"Taa-Haa",meaning:"Ta-Ha",verses:135,type:"Meccan",juz:16,nameMalayalam:"താഹാ"),
        SurahInfo(id:21,nameArabic:"الأنبياء",nameEnglish:"Al-Anbiya",nameTransliteration:"Al-Anbiyaa",meaning:"The Prophets",verses:112,type:"Meccan",juz:17,nameMalayalam:"അൽ-അൻബിയാ"),
        SurahInfo(id:22,nameArabic:"الحج",nameEnglish:"Al-Hajj",nameTransliteration:"Al-Hajj",meaning:"The Pilgrimage",verses:78,type:"Medinan",juz:17,nameMalayalam:"അൽ-ഹജ്‌ജ"),
        SurahInfo(id:23,nameArabic:"المؤمنون",nameEnglish:"Al-Muminun",nameTransliteration:"Al-Mu'minoon",meaning:"The Believers",verses:118,type:"Meccan",juz:18,nameMalayalam:"അൽ-മുമിനൂൻ"),
        SurahInfo(id:24,nameArabic:"النور",nameEnglish:"An-Nur",nameTransliteration:"An-Noor",meaning:"The Light",verses:64,type:"Medinan",juz:18,nameMalayalam:"അൻ-നൂർ"),
        SurahInfo(id:25,nameArabic:"الفرقان",nameEnglish:"Al-Furqan",nameTransliteration:"Al-Furqaan",meaning:"The Criterion",verses:77,type:"Meccan",juz:18,nameMalayalam:"അൽ-ഫുർഖാൻ"),
        SurahInfo(id:26,nameArabic:"الشعراء",nameEnglish:"Ash-Shuara",nameTransliteration:"Ash-Shu'araa",meaning:"The Poets",verses:227,type:"Meccan",juz:19,nameMalayalam:"അഷ്-ഷുഅറാ"),
        SurahInfo(id:27,nameArabic:"النمل",nameEnglish:"An-Naml",nameTransliteration:"An-Naml",meaning:"The Ant",verses:93,type:"Meccan",juz:19,nameMalayalam:"അൻ-നംല്"),
        SurahInfo(id:28,nameArabic:"القصص",nameEnglish:"Al-Qasas",nameTransliteration:"Al-Qasas",meaning:"The Stories",verses:88,type:"Meccan",juz:20,nameMalayalam:"അൽ-ഖസസ്"),
        SurahInfo(id:29,nameArabic:"العنكبوت",nameEnglish:"Al-Ankabut",nameTransliteration:"Al-'Ankaboot",meaning:"The Spider",verses:69,type:"Meccan",juz:20,nameMalayalam:"അൽ-അൻകബൂത്"),
        SurahInfo(id:30,nameArabic:"الروم",nameEnglish:"Ar-Rum",nameTransliteration:"Ar-Room",meaning:"The Romans",verses:60,type:"Meccan",juz:21,nameMalayalam:"അർ-റൂം"),
        SurahInfo(id:31,nameArabic:"لقمان",nameEnglish:"Luqman",nameTransliteration:"Luqman",meaning:"Luqman",verses:34,type:"Meccan",juz:21,nameMalayalam:"ലുഖ്‌മാൻ"),
        SurahInfo(id:32,nameArabic:"السجدة",nameEnglish:"As-Sajdah",nameTransliteration:"As-Sajda",meaning:"The Prostration",verses:30,type:"Meccan",juz:21,nameMalayalam:"അസ്-സജ്‌ദ"),
        SurahInfo(id:33,nameArabic:"الأحزاب",nameEnglish:"Al-Ahzab",nameTransliteration:"Al-Ahzaab",meaning:"The Combined Forces",verses:73,type:"Medinan",juz:21,nameMalayalam:"അൽ-അഹ്‌സാബ്"),
        SurahInfo(id:34,nameArabic:"سبأ",nameEnglish:"Saba",nameTransliteration:"Saba",meaning:"Sheba",verses:54,type:"Meccan",juz:22,nameMalayalam:"സബഅ്"),
        SurahInfo(id:35,nameArabic:"فاطر",nameEnglish:"Fatir",nameTransliteration:"Faatir",meaning:"Originator",verses:45,type:"Meccan",juz:22,nameMalayalam:"ഫാതിർ"),
        SurahInfo(id:36,nameArabic:"يس",nameEnglish:"Ya-Sin",nameTransliteration:"Yaseen",meaning:"Ya Sin",verses:83,type:"Meccan",juz:22,nameMalayalam:"യാസീൻ"),
        SurahInfo(id:37,nameArabic:"الصافات",nameEnglish:"As-Saffat",nameTransliteration:"As-Saaffaat",meaning:"Those in Ranks",verses:182,type:"Meccan",juz:23,nameMalayalam:"അസ്-സാഫാത്"),
        SurahInfo(id:38,nameArabic:"ص",nameEnglish:"Sad",nameTransliteration:"Saad",meaning:"The Letter Sad",verses:88,type:"Meccan",juz:23,nameMalayalam:"സാദ്"),
        SurahInfo(id:39,nameArabic:"الزمر",nameEnglish:"Az-Zumar",nameTransliteration:"Az-Zumar",meaning:"The Troops",verses:75,type:"Meccan",juz:23,nameMalayalam:"അസ്-സുമർ"),
        SurahInfo(id:40,nameArabic:"غافر",nameEnglish:"Ghafir",nameTransliteration:"Ghaafir",meaning:"The Forgiver",verses:85,type:"Meccan",juz:24,nameMalayalam:"ഗാഫിർ"),
        SurahInfo(id:41,nameArabic:"فصلت",nameEnglish:"Fussilat",nameTransliteration:"Fussilat",meaning:"Explained in Detail",verses:54,type:"Meccan",juz:24,nameMalayalam:"ഫുസ്സിലത്"),
        SurahInfo(id:42,nameArabic:"الشورى",nameEnglish:"Ash-Shura",nameTransliteration:"Ash-Shura",meaning:"The Consultation",verses:53,type:"Meccan",juz:25,nameMalayalam:"അഷ്-ഷൂറ"),
        SurahInfo(id:43,nameArabic:"الزخرف",nameEnglish:"Az-Zukhruf",nameTransliteration:"Az-Zukhruf",meaning:"The Ornaments",verses:89,type:"Meccan",juz:25,nameMalayalam:"അസ്-സുഖ്‌റുഫ്"),
        SurahInfo(id:44,nameArabic:"الدخان",nameEnglish:"Ad-Dukhan",nameTransliteration:"Ad-Dukhaan",meaning:"The Smoke",verses:59,type:"Meccan",juz:25,nameMalayalam:"അദ്-ദുഖാൻ"),
        SurahInfo(id:45,nameArabic:"الجاثية",nameEnglish:"Al-Jathiyah",nameTransliteration:"Al-Jaathiya",meaning:"The Crouching",verses:37,type:"Meccan",juz:25,nameMalayalam:"അൽ-ജാസിയ"),
        SurahInfo(id:46,nameArabic:"الأحقاف",nameEnglish:"Al-Ahqaf",nameTransliteration:"Al-Ahqaf",meaning:"The Wind-Curved Sandhills",verses:35,type:"Meccan",juz:26,nameMalayalam:"അൽ-അഹ്‌ഖാഫ്"),
        SurahInfo(id:47,nameArabic:"محمد",nameEnglish:"Muhammad",nameTransliteration:"Muhammad",meaning:"Muhammad",verses:38,type:"Medinan",juz:26,nameMalayalam:"മുഹമ്മദ്"),
        SurahInfo(id:48,nameArabic:"الفتح",nameEnglish:"Al-Fath",nameTransliteration:"Al-Fath",meaning:"The Victory",verses:29,type:"Medinan",juz:26,nameMalayalam:"അൽ-ഫത്ത്"),
        SurahInfo(id:49,nameArabic:"الحجرات",nameEnglish:"Al-Hujurat",nameTransliteration:"Al-Hujuraat",meaning:"The Rooms",verses:18,type:"Medinan",juz:26,nameMalayalam:"അൽ-ഹുജുറാത്"),
        SurahInfo(id:50,nameArabic:"ق",nameEnglish:"Qaf",nameTransliteration:"Qaaf",meaning:"The Letter Qaf",verses:45,type:"Meccan",juz:26,nameMalayalam:"ഖാഫ്"),
        SurahInfo(id:51,nameArabic:"الذاريات",nameEnglish:"Adh-Dhariyat",nameTransliteration:"Adh-Dhaariyat",meaning:"The Winnowing Winds",verses:60,type:"Meccan",juz:26,nameMalayalam:"അസ്-സാരിയാത്"),
        SurahInfo(id:52,nameArabic:"الطور",nameEnglish:"At-Tur",nameTransliteration:"At-Tur",meaning:"The Mount",verses:49,type:"Meccan",juz:27,nameMalayalam:"അത്-തൂർ"),
        SurahInfo(id:53,nameArabic:"النجم",nameEnglish:"An-Najm",nameTransliteration:"An-Najm",meaning:"The Star",verses:62,type:"Meccan",juz:27,nameMalayalam:"അൻ-നജ്‌മ്"),
        SurahInfo(id:54,nameArabic:"القمر",nameEnglish:"Al-Qamar",nameTransliteration:"Al-Qamar",meaning:"The Moon",verses:55,type:"Meccan",juz:27,nameMalayalam:"അൽ-ഖമർ"),
        SurahInfo(id:55,nameArabic:"الرحمن",nameEnglish:"Ar-Rahman",nameTransliteration:"Ar-Rahmaan",meaning:"The Beneficent",verses:78,type:"Medinan",juz:27,nameMalayalam:"അർ-റഹ്‌മാൻ"),
        SurahInfo(id:56,nameArabic:"الواقعة",nameEnglish:"Al-Waqiah",nameTransliteration:"Al-Waqi'a",meaning:"The Inevitable",verses:96,type:"Meccan",juz:27,nameMalayalam:"അൽ-വാഖിഅ"),
        SurahInfo(id:57,nameArabic:"الحديد",nameEnglish:"Al-Hadid",nameTransliteration:"Al-Hadid",meaning:"The Iron",verses:29,type:"Medinan",juz:27,nameMalayalam:"അൽ-ഹദീദ്"),
        SurahInfo(id:58,nameArabic:"المجادلة",nameEnglish:"Al-Mujadila",nameTransliteration:"Al-Mujaadila",meaning:"The Pleading Woman",verses:22,type:"Medinan",juz:28,nameMalayalam:"അൽ-മുജാദില"),
        SurahInfo(id:59,nameArabic:"الحشر",nameEnglish:"Al-Hashr",nameTransliteration:"Al-Hashr",meaning:"The Exile",verses:24,type:"Medinan",juz:28,nameMalayalam:"അൽ-ഹഷ്‌ർ"),
        SurahInfo(id:60,nameArabic:"الممتحنة",nameEnglish:"Al-Mumtahanah",nameTransliteration:"Al-Mumtahana",meaning:"She That is Examined",verses:13,type:"Medinan",juz:28,nameMalayalam:"അൽ-മുംതഹിന"),
        SurahInfo(id:61,nameArabic:"الصف",nameEnglish:"As-Saf",nameTransliteration:"As-Saff",meaning:"The Ranks",verses:14,type:"Medinan",juz:28,nameMalayalam:"അസ്-സഫ്"),
        SurahInfo(id:62,nameArabic:"الجمعة",nameEnglish:"Al-Jumuah",nameTransliteration:"Al-Jumu'a",meaning:"The Congregation",verses:11,type:"Medinan",juz:28,nameMalayalam:"അൽ-ജുമുഅ"),
        SurahInfo(id:63,nameArabic:"المنافقون",nameEnglish:"Al-Munafiqun",nameTransliteration:"Al-Munaafiqoon",meaning:"The Hypocrites",verses:11,type:"Medinan",juz:28,nameMalayalam:"അൽ-മുനാഫിഖൂൻ"),
        SurahInfo(id:64,nameArabic:"التغابن",nameEnglish:"At-Taghabun",nameTransliteration:"At-Taghaabun",meaning:"The Mutual Disillusion",verses:18,type:"Medinan",juz:28,nameMalayalam:"അത്തഗാബുൻ"),
        SurahInfo(id:65,nameArabic:"الطلاق",nameEnglish:"At-Talaq",nameTransliteration:"At-Talaaq",meaning:"The Divorce",verses:12,type:"Medinan",juz:28,nameMalayalam:"അത്തലക്"),
        SurahInfo(id:66,nameArabic:"التحريم",nameEnglish:"At-Tahrim",nameTransliteration:"At-Tahrim",meaning:"The Prohibition",verses:12,type:"Medinan",juz:28,nameMalayalam:"അത്തഹ്‌രീം"),
        SurahInfo(id:67,nameArabic:"الملك",nameEnglish:"Al-Mulk",nameTransliteration:"Al-Mulk",meaning:"The Sovereignty",verses:30,type:"Meccan",juz:29,nameMalayalam:"അൽ-മുൽക്"),
        SurahInfo(id:68,nameArabic:"القلم",nameEnglish:"Al-Qalam",nameTransliteration:"Al-Qalam",meaning:"The Pen",verses:52,type:"Meccan",juz:29,nameMalayalam:"അൽ-ഖലം"),
        SurahInfo(id:69,nameArabic:"الحاقة",nameEnglish:"Al-Haqqah",nameTransliteration:"Al-Haaqqa",meaning:"The Reality",verses:52,type:"Meccan",juz:29,nameMalayalam:"അൽ-ഹാക്ക"),
        SurahInfo(id:70,nameArabic:"المعارج",nameEnglish:"Al-Maarij",nameTransliteration:"Al-Ma'aarij",meaning:"The Ascending Stairways",verses:44,type:"Meccan",juz:29,nameMalayalam:"അൽ-മഅാരിജ്"),
        SurahInfo(id:71,nameArabic:"نوح",nameEnglish:"Nuh",nameTransliteration:"Nooh",meaning:"Noah",verses:28,type:"Meccan",juz:29,nameMalayalam:"നൂഹ്"),
        SurahInfo(id:72,nameArabic:"الجن",nameEnglish:"Al-Jinn",nameTransliteration:"Al-Jinn",meaning:"The Jinn",verses:28,type:"Meccan",juz:29,nameMalayalam:"അൽ-ജിന്ന്"),
        SurahInfo(id:73,nameArabic:"المزمل",nameEnglish:"Al-Muzzammil",nameTransliteration:"Al-Muzzammil",meaning:"The Enshrouded One",verses:20,type:"Meccan",juz:29,nameMalayalam:"അൽ-മുസ്സമ്മിൽ"),
        SurahInfo(id:74,nameArabic:"المدثر",nameEnglish:"Al-Muddaththir",nameTransliteration:"Al-Muddaththir",meaning:"The Cloaked One",verses:56,type:"Meccan",juz:29,nameMalayalam:"അൽ-മുദ്ദഥിർ"),
        SurahInfo(id:75,nameArabic:"القيامة",nameEnglish:"Al-Qiyamah",nameTransliteration:"Al-Qiyaama",meaning:"The Resurrection",verses:40,type:"Meccan",juz:29,nameMalayalam:"അൽ-ഖിയാമ"),
        SurahInfo(id:76,nameArabic:"الإنسان",nameEnglish:"Al-Insan",nameTransliteration:"Al-Insaan",meaning:"The Man",verses:31,type:"Medinan",juz:29,nameMalayalam:"അൽ-ഇൻസാൻ"),
        SurahInfo(id:77,nameArabic:"المرسلات",nameEnglish:"Al-Mursalat",nameTransliteration:"Al-Mursalaat",meaning:"The Emissaries",verses:50,type:"Meccan",juz:29,nameMalayalam:"അൽ-മുർസഽത്"),
        SurahInfo(id:78,nameArabic:"النبأ",nameEnglish:"An-Naba",nameTransliteration:"An-Naba",meaning:"The Tidings",verses:40,type:"Meccan",juz:30,nameMalayalam:"അൻ-നബഅ്"),
        SurahInfo(id:79,nameArabic:"النازعات",nameEnglish:"An-Naziat",nameTransliteration:"An-Naazi'aat",meaning:"Those Who Drag Forth",verses:46,type:"Meccan",juz:30,nameMalayalam:"അൻ-നാസിആത്"),
        SurahInfo(id:80,nameArabic:"عبس",nameEnglish:"Abasa",nameTransliteration:"'Abasa",meaning:"He Frowned",verses:42,type:"Meccan",juz:30,nameMalayalam:"അബസ"),
        SurahInfo(id:81,nameArabic:"التكوير",nameEnglish:"At-Takwir",nameTransliteration:"At-Takwir",meaning:"The Overthrowing",verses:29,type:"Meccan",juz:30,nameMalayalam:"അത്തക്വീർ"),
        SurahInfo(id:82,nameArabic:"الإنفطار",nameEnglish:"Al-Infitar",nameTransliteration:"Al-Infitaar",meaning:"The Cleaving",verses:19,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഇൻഫിതാർ"),
        SurahInfo(id:83,nameArabic:"المطففين",nameEnglish:"Al-Mutaffifin",nameTransliteration:"Al-Mutaffifin",meaning:"The Defrauding",verses:36,type:"Meccan",juz:30,nameMalayalam:"അൽ-മുതഫ്ഫിഫീൻ"),
        SurahInfo(id:84,nameArabic:"الانشقاق",nameEnglish:"Al-Inshiqaq",nameTransliteration:"Al-Inshiqaaq",meaning:"The Sundering",verses:25,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഇൻഷിഖാഖ്"),
        SurahInfo(id:85,nameArabic:"البروج",nameEnglish:"Al-Buruj",nameTransliteration:"Al-Burooj",meaning:"The Mansions of Stars",verses:22,type:"Meccan",juz:30,nameMalayalam:"അൽ-ബുറൂജ്"),
        SurahInfo(id:86,nameArabic:"الطارق",nameEnglish:"At-Tariq",nameTransliteration:"At-Taariq",meaning:"The Nightcomer",verses:17,type:"Meccan",juz:30,nameMalayalam:"അത്താരിഖ്"),
        SurahInfo(id:87,nameArabic:"الأعلى",nameEnglish:"Al-Ala",nameTransliteration:"Al-A'laa",meaning:"The Most High",verses:19,type:"Meccan",juz:30,nameMalayalam:"അൽ-അലാ"),
        SurahInfo(id:88,nameArabic:"الغاشية",nameEnglish:"Al-Ghashiyah",nameTransliteration:"Al-Ghaashiya",meaning:"The Overwhelming",verses:26,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഘാഷിയ"),
        SurahInfo(id:89,nameArabic:"الفجر",nameEnglish:"Al-Fajr",nameTransliteration:"Al-Fajr",meaning:"The Dawn",verses:30,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഫജ്‌ർ"),
        SurahInfo(id:90,nameArabic:"البلد",nameEnglish:"Al-Balad",nameTransliteration:"Al-Balad",meaning:"The City",verses:20,type:"Meccan",juz:30,nameMalayalam:"അൽ-ബലദ്"),
        SurahInfo(id:91,nameArabic:"الشمس",nameEnglish:"Ash-Shams",nameTransliteration:"Ash-Shams",meaning:"The Sun",verses:15,type:"Meccan",juz:30,nameMalayalam:"അഷ്-ഷംസ്"),
        SurahInfo(id:92,nameArabic:"الليل",nameEnglish:"Al-Layl",nameTransliteration:"Al-Lail",meaning:"The Night",verses:21,type:"Meccan",juz:30,nameMalayalam:"അൽ-ലില്"),
        SurahInfo(id:93,nameArabic:"الضحى",nameEnglish:"Ad-Duhaa",nameTransliteration:"Ad-Dhuhaa",meaning:"The Morning Hours",verses:11,type:"Meccan",juz:30,nameMalayalam:"അദ്-ദുഹാ"),
        SurahInfo(id:94,nameArabic:"الشرح",nameEnglish:"Ash-Sharh",nameTransliteration:"Ash-Sharh",meaning:"The Relief",verses:8,type:"Meccan",juz:30,nameMalayalam:"അഷ്-ഷർഹ്"),
        SurahInfo(id:95,nameArabic:"التين",nameEnglish:"At-Tin",nameTransliteration:"At-Tin",meaning:"The Fig",verses:8,type:"Meccan",juz:30,nameMalayalam:"അത്തീന്"),
        SurahInfo(id:96,nameArabic:"العلق",nameEnglish:"Al-Alaq",nameTransliteration:"Al-'Alaq",meaning:"The Clot",verses:19,type:"Meccan",juz:30,nameMalayalam:"അൽ-അലഖ്"),
        SurahInfo(id:97,nameArabic:"القدر",nameEnglish:"Al-Qadr",nameTransliteration:"Al-Qadr",meaning:"The Power",verses:5,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഖദ്‌ർ"),
        SurahInfo(id:98,nameArabic:"البينة",nameEnglish:"Al-Bayyinah",nameTransliteration:"Al-Bayyina",meaning:"The Clear Proof",verses:8,type:"Medinan",juz:30,nameMalayalam:"അൽ-ബയ്‌യിന"),
        SurahInfo(id:99,nameArabic:"الزلزلة",nameEnglish:"Az-Zalzalah",nameTransliteration:"Az-Zalzala",meaning:"The Earthquake",verses:8,type:"Medinan",juz:30,nameMalayalam:"അസ്-സൽസല"),
        SurahInfo(id:100,nameArabic:"العاديات",nameEnglish:"Al-Adiyat",nameTransliteration:"Al-'Aadiyaat",meaning:"The Courser",verses:11,type:"Meccan",juz:30,nameMalayalam:"അൽ-ആദിയാത്"),
        SurahInfo(id:101,nameArabic:"القارعة",nameEnglish:"Al-Qariah",nameTransliteration:"Al-Qaari'a",meaning:"The Calamity",verses:11,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഖാറിഅ"),
        SurahInfo(id:102,nameArabic:"التكاثر",nameEnglish:"At-Takathur",nameTransliteration:"At-Takaathur",meaning:"The Rivalry",verses:8,type:"Meccan",juz:30,nameMalayalam:"അത്തകാതുർ"),
        SurahInfo(id:103,nameArabic:"العصر",nameEnglish:"Al-Asr",nameTransliteration:"Al-'Asr",meaning:"The Declining Day",verses:3,type:"Meccan",juz:30,nameMalayalam:"അൽ-അസ്‌ർ"),
        SurahInfo(id:104,nameArabic:"الهمزة",nameEnglish:"Al-Humazah",nameTransliteration:"Al-Humaza",meaning:"The Traducer",verses:9,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഹുമസ"),
        SurahInfo(id:105,nameArabic:"الفيل",nameEnglish:"Al-Fil",nameTransliteration:"Al-Fil",meaning:"The Elephant",verses:5,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഫിൽ"),
        SurahInfo(id:106,nameArabic:"قريش",nameEnglish:"Quraysh",nameTransliteration:"Quraish",meaning:"Quraysh",verses:4,type:"Meccan",juz:30,nameMalayalam:"ഖുറൈഷ്"),
        SurahInfo(id:107,nameArabic:"الماعون",nameEnglish:"Al-Maun",nameTransliteration:"Al-Maa'oon",meaning:"The Small Kindnesses",verses:7,type:"Meccan",juz:30,nameMalayalam:"അൽ-മാഊൻ"),
        SurahInfo(id:108,nameArabic:"الكوثر",nameEnglish:"Al-Kawthar",nameTransliteration:"Al-Kawthar",meaning:"The Abundance",verses:3,type:"Meccan",juz:30,nameMalayalam:"അൽ-കവതർ"),
        SurahInfo(id:109,nameArabic:"الكافرون",nameEnglish:"Al-Kafirun",nameTransliteration:"Al-Kaafiroon",meaning:"The Disbelievers",verses:6,type:"Meccan",juz:30,nameMalayalam:"അൽ-കാഫിറൂൻ"),
        SurahInfo(id:110,nameArabic:"النصر",nameEnglish:"An-Nasr",nameTransliteration:"An-Nasr",meaning:"The Divine Support",verses:3,type:"Medinan",juz:30,nameMalayalam:"അൻ-നസ്‌ർ"),
        SurahInfo(id:111,nameArabic:"المسد",nameEnglish:"Al-Masad",nameTransliteration:"Al-Masad",meaning:"The Palm Fiber",verses:5,type:"Meccan",juz:30,nameMalayalam:"അൽ-മസദ്"),
        SurahInfo(id:112,nameArabic:"الإخلاص",nameEnglish:"Al-Ikhlas",nameTransliteration:"Al-Ikhlaas",meaning:"The Sincerity",verses:4,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഇഖ്‌ലാസ്"),
        SurahInfo(id:113,nameArabic:"الفلق",nameEnglish:"Al-Falaq",nameTransliteration:"Al-Falaq",meaning:"The Daybreak",verses:5,type:"Meccan",juz:30,nameMalayalam:"അൽ-ഫലഖ്"),
        SurahInfo(id:114,nameArabic:"الناس",nameEnglish:"An-Nas",nameTransliteration:"An-Naas",meaning:"Mankind",verses:6,type:"Medinan",juz:30,nameMalayalam:"അൻ-നാസ്"),
    ]
}
